// Prepcore — Admin Dashboard
import { CheckCircle2, Gift } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { createServiceRoleClient } from "@/services/supabase/admin";

const naira = (amount: number) => amount.toLocaleString("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 });

export default async function ReferralRewardsPage() {
  const admin = createServiceRoleClient();
  const { data: rewards, error } = await admin.from("user_referral_rewards").select("*").order("created_at", { ascending: false });
  const userIds = [...new Set((rewards ?? []).map((reward) => reward.user_id))];
  const { data: users } = userIds.length ? await admin.from("users").select("id, full_name, email").in("id", userIds) : { data: [] };
  const userMap = new Map((users ?? []).map((user) => [user.id, user]));
  const pending = (rewards ?? []).filter((reward) => reward.cash_claimed && !reward.admin_paid).length;
  const paid = (rewards ?? []).filter((reward) => reward.admin_paid).length;
  const proGranted = (rewards ?? []).filter((reward) => reward.pro_granted).length;
  return <div className="space-y-6"><div><h1 className="flex items-center gap-2 text-3xl font-bold text-navy"><Gift className="h-7 w-7 text-primary" />Referral reward claims</h1><p className="mt-2 text-sm text-slate-600">Track earned Pro months and ₦5,000 referral cash rewards.</p></div>{error ? <Card className="border-red-200"><CardContent className="p-5 text-sm text-destructive">Unable to load reward claims: {error.message}</CardContent></Card> : <><div className="grid gap-4 md:grid-cols-3"><Card className="rounded-2xl border-border bg-white shadow-sm"><CardContent className="p-5"><p className="text-sm text-slate-500">Pending payment</p><p className="mt-2 text-3xl font-bold text-amber-600">{pending}</p></CardContent></Card><Card className="rounded-2xl border-border bg-white shadow-sm"><CardContent className="p-5"><p className="text-sm text-slate-500">Total paid out</p><p className="mt-2 text-3xl font-bold text-navy">{naira(paid * 5000)}</p><p className="mt-1 text-xs text-slate-500">{paid} paid claim{paid === 1 ? "" : "s"}</p></CardContent></Card><Card className="rounded-2xl border-border bg-white shadow-sm"><CardContent className="p-5"><p className="text-sm text-slate-500">Pro months granted</p><p className="mt-2 text-3xl font-bold text-navy">{proGranted}</p></CardContent></Card></div><Card className="rounded-2xl border-border bg-white shadow-sm"><CardHeader><CardTitle>Reward records</CardTitle></CardHeader><CardContent className="overflow-x-auto">{(rewards ?? []).length === 0 ? <p className="text-sm text-slate-500">No referral reward records yet.</p> : <table className="w-full text-sm"><thead className="border-b text-left text-slate-500"><tr><th className="p-3">Referrer</th><th className="p-3">Batch</th><th className="p-3">Pro reward</th><th className="p-3">Bank details</th><th className="p-3">Cash status</th></tr></thead><tbody>{(rewards ?? []).map((reward) => { const user = userMap.get(reward.user_id); const cashStatus = reward.admin_paid ? "Paid" : reward.cash_claimed ? "Pending payment" : "Not claimed"; return <tr key={reward.id} className="border-b border-border/60 hover:bg-slate-50"><td className="p-3"><p className="font-medium text-navy">{user?.full_name || "Unknown user"}</p><p className="text-xs text-slate-500">{user?.email || ""}</p></td><td className="p-3">#{reward.reward_batch}</td><td className="p-3">{reward.pro_granted ? <span className="inline-flex items-center gap-1 text-green-700"><CheckCircle2 className="h-4 w-4" />Granted</span> : "Pending"}</td><td className="p-3 text-xs text-slate-600">{reward.cash_claimed ? <>{reward.bank_name}<br />{reward.account_number}<br />{reward.account_name}</> : "—"}</td><td className="p-3"><span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold ${reward.admin_paid ? "bg-green-100 text-green-700" : reward.cash_claimed ? "bg-amber-100 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{cashStatus}</span></td></tr>; })}</tbody></table>}</CardContent></Card></>}</div>;
}
